### ISSUE TITLE
ArrowFunction vs Function

### ISSUE THREAD

**Issue by fuhrmanator** [fuhrmanator/FamixTypeScript#22]
Should the metamodel distinguish between a Function and an ArrowFunction?

ts-morph certainly does (currently the importer doesn't find ArrowFunction as far as I know).

Compared to Functions, ArrowFunctions don't have a name, and there's a "this" context/binding (not sure if it's important in a MM).

**Comment by NicolasAnquetil** [comment]
if ts-morph distinguishes them, then it is probably a good idea to do it also in the meta-model

**Comment by fuhrmanator** [comment]
fixed in #18
